### ISSUE TITLE
xml:id required

### ISSUE THREAD

**Issue by fsanzl** [fun-with-editions/staribacher-data#5]
Data files should have a xml:id

**Comment by csae8092** [comment]
have look at 
https://github.com/acdh-oeaw/acdh-tei-pyutils?tab=readme-ov-file#command-line-scripts

**Comment by fsanzl** [comment]
> have look at https://github.com/acdh-oeaw/acdh-tei-pyutils?tab=readme-ov-file#command-line-scripts

Ooops, I've just merged a fix. Anyway, I will use the ACDH lib next time instead of reinventing the wheel, now that I know it can do it quicker and easier.
